apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  selector: { matchLabels: { app: customer } }
  template:
    metadata: { labels: { app: customer } }
    spec:
      containers:
        - name: customer
          image: REPLACE_ME/customer:TAG
          env:
            - { name: POSTGRES_HOST, value: "customer-db" }
            - { name: POSTGRES_DB, value: "customers" }
            - { name: POSTGRES_USER, value: "postgres" }
            - { name: POSTGRES_PASSWORD, value: "postgres" }
          ports: [{ containerPort: 8000 }]
          startupProbe:
            httpGet: { path: "/", port: 8000 }
            failureThreshold: 30 # 30*5s = 150s
            periodSeconds: 5
          readinessProbe:
            httpGet: { path: "/", port: 8000 }
            initialDelaySeconds: 20
            periodSeconds: 5

          livenessProbe:
            httpGet: { path: "/", port: 8000 }
            initialDelaySeconds: 40
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: customer
spec:
  selector: { app: customer }
  ports: [{ port: 8000, targetPort: 8000 }]
  type: ClusterIP
