apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 1
  selector: { matchLabels: { app: product } }
  template:
    metadata: { labels: { app: product } }
    spec:
      containers:
        - name: product
          # ACR image set in CI via kubectl set image
          image: REPLACE_ME/product:TAG
          env:
            - { name: POSTGRES_HOST, value: "product-db" }
            - { name: POSTGRES_DB, value: "products" }
            - { name: POSTGRES_USER, value: "postgres" }
            - { name: POSTGRES_PASSWORD, value: "postgres" }
          ports: [{ containerPort: 8000 }]
          readinessProbe:
            httpGet: { path: "/", port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: 8000 }
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  selector: { app: product }
  ports: [{ port: 8000, targetPort: 8000 }]
  type: ClusterIP

